version: "3"

services:
  api:
    build: ./server/
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/app
    container_name: api_container
  react:
    build: ./client/
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    image: hugolima/react-client
    container_name: react_container
    command: npm start
